### ISSUE TITLE
Github workflow switch to use mamba

### ISSUE THREAD

**Issue by ylyangtw** [IN-CORE/pyincore#378]
Here is what works for `pytests.yml`
However, if we run multiple pytests simultaneously, pytests probably may fail because they are accessing/updating dev mongo at the same time. This issue needs to be fixed.

```
name: pytests

# Runs unit tests on:
#  - any push to any branch
#  - when a PR is opened/reopened - this is just for additional safety and covers the case of main -> develop PRs without new pushes

# TODO: Use mamba instead of conda for installing packages. Improves on ~5mins it takes to install requirements.
#  https://github.com/mamba-org/provision-with-micromamba

on:
  push:

  pull_request:
     types: [opened, reopened]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    name: Python ${{ matrix.python-version }} Test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          create-args: >-
            python=${{ matrix.python-version }}
            pytest
          environment-file: environment.yml
          generate-run-shell: true

      - name: Run tests with pytest
        run: |
          echo "${{secrets.PYTEST_USER_TOKEN}}" > tests/pyincore/.incorepw
          python -m pytest --ignore=tests/test_format.py --ignore=tests/pyincore/analyses
        shell: micromamba-shell {0}

```
