### ISSUE TITLE
Install precommit hook on pyincore

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#500]
Python can leverage the black library;
**Make sure we be careful around all the CGE analyses though** 

an example see: 
```
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
```

Clowder example:
https://github.com/clowder-framework/clowder2/pull/846
